In [127]:
import pandas as pd

#основні дані
df = pd.read_csv('survey_results_public.csv', low_memory=False)

# опис питань
schema_df = pd.read_csv('survey_results_schema.csv')

In [128]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), object(119)
memory usage: 64.6+ MB

In [129]:
df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

__1. Підрахунок загальної кількості респондентів:__

In [130]:
df.shape[0]

49191

__2. Аналіз повноти відповідей респондентів:__

In [131]:
schema_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   qid       139 non-null    object
 1   qname     139 non-null    object
 2   question  139 non-null    object
 3   type      139 non-null    object
 4   sub       49 non-null     object
 5   sq_id     49 non-null     float64
dtypes: float64(1), object(5)
memory usage: 6.6+ KB

In [132]:
#Отримати список питань з файлу survey_results_schema (поле "qname")
schema_df['qname'].unique()

array(['TechEndorse_1', 'TechEndorse_2', 'TechEndorse_3', 'TechEndorse_4',
       'TechEndorse_5', 'TechEndorse_6', 'TechEndorse_7', 'TechEndorse_8',
       'TechEndorse_9', 'TechEndorse_13', 'TechEndorse_13_TEXT',
       'TechOppose_1', 'TechOppose_2', 'TechOppose_3', 'TechOppose_5',
       'TechOppose_7', 'TechOppose_9', 'TechOppose_11', 'TechOppose_13',
       'TechOppose_16', 'TechOppose_15', 'TechOppose_15_TEXT',
       'JobSatPoints_1', 'JobSatPoints_2', 'JobSatPoints_16',
       'JobSatPoints_3', 'JobSatPoints_4', 'JobSatPoints_5',
       'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8',
       'JobSatPoints_9', 'JobSatPoints_10', 'JobSatPoints_11',
       'JobSatPoints_13', 'JobSatPoints_14', 'JobSatPoints_15',
       'JobSatPoints_15_TEXT', 'SO_Actions_1', 'SO_Actions_16',
       'SO_Actions_3', 'SO_Actions_4', 'SO_Actions_5', 'SO_Actions_6',
       'SO_Actions_9', 'SO_Actions_7', 'SO_Actions_10', 'SO_Actions_15',
       'SO_Actions_15_TEXT', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI', 'AILearnHow', 'YearsCode', 'DevType', 'OrgSize',
       'ICorPM', 'RemoteWork', 'PurchaseInfluence', 'TechEndorseIntro',
       'Industry', 'JobSat', 'AIThreat', 'NewRole', 'ToolCountWork',
       'ToolCountPersonal', 'Country', 'Currency', 'CompTotal',
       'LanguageChoice', 'Language', 'LanguagesHaveEntry',
       'LanguagesWantEntry', 'DatabaseChoice', 'Database',
       'DatabaseHaveEntry', 'DatabaseWantEntry', 'PlatformChoice',
       'Platform', 'PlatformHaveEntry', 'PlatformWantEntry',
       'WebframeChoice', 'Webframe', 'WebframeHaveEntry',
       'WebframeWantEntry', 'DevEnvsChoice', 'DevEnvs', 'DevEnvHaveEntry',
       'DevEnvWantEntry', 'SOTags', 'SOTagsHaveEntry', 'SOTagsWant Entry',
       'OpSys', 'OfficeStackAsync', 'OfficeStackHaveEntry',
       'OfficeStackWantEntry', 'CommPlatform', 'CommPlatformHaveEntr',
       'CommPlatformWantEntr', 'AIModelsChoice', 'AIModels',
       'AIModelsHaveEntry', 'AIModelsWantEntry', 'SOAccount',
       'SOVisitFreq', 'SODuration', 'SOPartFreq', 'SO_Dev_Content',
       'SOComm', 'SOFriction', 'AISelect', 'AISent', 'AIAcc', 'AIComplex',
       'AITool', 'AIFrustration', 'AIExplain', 'AIAgents',
       'AIAgentChange', 'AIAgent_Uses', 'AgentUsesGeneral',
       'AIAgentImpact', 'AIAgentChallenges', 'AIAgentKnowledge',
       'AIAgentKnowWrite', 'AIAgentOrchestration', 'AIAgentOrchWrite',
       'AIAgentObserveSecure', 'AIAgentObsWrite', 'AIAgentExternal',
       'AIAgentExtWrite', 'AIHuman', 'AIOpen'], dtype=object)

In [133]:
len(schema_df['qname'])

139

In [134]:
questions_from_schema = set(schema_df['qname'])   #питання зі схеми
columns_in_df = set(df.columns)                   #колонки з основної таблиці

#спільні назви (інтерсекція)
common_columns = list(questions_from_schema.intersection(columns_in_df))
print(len(common_columns))

126

In [135]:
count_resp = len(df[common_columns].dropna())
print(f"Кількість респондентів, які відповіли на всі запитання з опитування:{count_resp}")

Кількість респондентів, які відповіли на всі запитання з опитування:0

__3. Статистичний аналіз досвіду респондентів:__

In [136]:
#показники для колонки WorkExp
mean_val = df['WorkExp'].mean()
median_val = df['WorkExp'].median()
mode_val = df['WorkExp'].mode()[0] # Мода повертає список, тому обрано перший елемент


print(f"Середній досвід роботи: {mean_val:.2f} років")
print(f"Медіанний досвід роботи: {median_val} років")
print(f"Найпопулярніший досвід роботи(мода): {mode_val} років")

Середній досвід роботи: 13.37 років
Медіанний досвід роботи: 10.0 років
Найпопулярніший досвід роботи(мода): 10.0 років

__4. Аналіз віддаленої роботи:__

In [137]:
df['RemoteWork'].value_counts()   # унікальні значення в колонці RemoteWork

RemoteWork
Remote                                                                          10931
Hybrid (some remote, leans heavy to in-person)                                   6732
In-person                                                                        6042
Hybrid (some in-person, leans heavy to flexibility)                              5831
Your choice (very flexible, you can come in when you want or just as needed)     4244
Name: count, dtype: int64

In [138]:
# Фільтр респондентів
remote_workers = df[df['RemoteWork'] == 'Remote']

#кількість респондентів
remote_count = len(remote_workers)
print(f"Кількість респондентів, що працюють віддалено: {remote_count}")

Кількість респондентів, що працюють віддалено: 10931

__5. Визначення популярності Python:__

In [139]:
[col for col in df.columns if 'Language' in col]

['LanguageChoice',
 'LanguageHaveWorkedWith',
 'LanguageWantToWorkWith',
 'LanguageAdmired',
 'LanguagesHaveEntry',
 'LanguagesWantEntry']

In [140]:
df['LanguageHaveWorkedWith'].head()

0                     Bash/Shell (all shells);Dart;SQL
1                                                 Java
2                  Dart;HTML/CSS;JavaScript;TypeScript
3                                      Java;Kotlin;SQL
4    C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...
Name: LanguageHaveWorkedWith, dtype: object

In [141]:
python_users = df['LanguageHaveWorkedWith'].apply(lambda x: 'Python' in str(x))

python_count = python_users.sum()   # кількість тих, хто знає Python
python_count

np.int64(18466)

In [142]:
percent = (python_count / df['LanguageHaveWorkedWith'].count()) * 100

print(f"Відсоток респондентів, які програмують на Python: {round(percent, 1)}%")

Відсоток респондентів, які програмують на Python: 58.3%

__6. Аналіз шляхів навчання програмуванню:__

In [143]:
[col for col in df.columns if 'Learn' in col]

['LearnCodeChoose', 'LearnCode', 'LearnCodeAI', 'AILearnHow']

In [144]:
df[['LearnCodeChoose', 'LearnCode', 'LearnCodeAI', 'AILearnHow']].head()

,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow
0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps
1,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps
2,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...
3,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...
4,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...

In [145]:
total = df['LearnCode'].apply(lambda x: 'Online Courses' in str(x)).sum()

print(f"Кількість респондентів, які навчалися через онлайн-курси: {total}")

Кількість респондентів, які навчалися через онлайн-курси: 10973

__7. Географічний аналіз компенсації Python-розробників:__

In [146]:
python_df = df[python_users].copy()   #всі рядки з df, де python_users True

In [147]:
#середнє та медіана для зарплати
salary_analysis = python_df.groupby('Country')['ConvertedCompYearly'].agg(['mean', 'median'])
salary_analysis.columns = ['Mean salary', 'Median salary']
salary_analysis

                                        Mean salary  Median salary
Country
Afghanistan                            22328.666667         1000.0
Albania                                47217.600000        50000.0
Algeria                                20187.285714         7088.0
Andorra                               226103.500000       226103.5
Angola                                          NaN            NaN
...                                             ...            ...
Venezuela, Bolivarian Republic of...    9908.647059         3000.0
Viet Nam                              218837.166667         8254.0
Yemen                                  32929.500000        23672.0
Zambia                                  5424.250000         3206.0
Zimbabwe                               34000.000000        25500.0

[167 rows x 2 columns]

__8. Аналіз освіти найбільш оплачуваних спеціалістів:__

In [148]:
clean_df = df.loc[df['ConvertedCompYearly'].notna()]  # очищений від порожніх значень 

# сортуємо та беремо топ
sort_df = clean_df.sort_values('ConvertedCompYearly', ascending=False)
result = sort_df[['ConvertedCompYearly', 'EdLevel']].head(5)
result

       ConvertedCompYearly                                          EdLevel
34267           50000000.0              Associate degree (A.A., A.S., etc.)
28700           33552715.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
43143           18387548.0              Associate degree (A.A., A.S., etc.)
35353           15430267.0     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
45971           13921760.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)

__9. Аналіз популярності Python по віковим категоріям:__

In [149]:
print([col for col in df.columns if 'Age' in col])

['Age', 'AIAgents', 'AIAgentChange', 'AIAgent_Uses', 'AgentUsesGeneral', 'AIAgentImpactSomewhat agree', 'AIAgentImpactNeutral', 'AIAgentImpactSomewhat disagree', 'AIAgentImpactStrongly agree', 'AIAgentImpactStrongly disagree', 'AIAgentChallengesNeutral', 'AIAgentChallengesSomewhat disagree', 'AIAgentChallengesStrongly agree', 'AIAgentChallengesSomewhat agree', 'AIAgentChallengesStrongly disagree', 'AIAgentKnowledge', 'AIAgentKnowWrite', 'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure', 'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite']

In [150]:
df['Age'].unique()

array(['25-34 years old', '35-44 years old', '45-54 years old',
       '18-24 years old', '65 years or older', '55-64 years old',
       'Prefer not to say'], dtype=object)

In [165]:
result = (python_users.groupby(df['Age']).mean() * 100).round(1)
result_table = result.reset_index()
result_table.columns = ['Age', '% Python']
result_table

                 Age  % Python
0    18-24 years old      40.0
1    25-34 years old      36.9
2    35-44 years old      36.7
3    45-54 years old      38.6
4    55-64 years old      37.2
5  65 years or older      31.6
6  Prefer not to say      31.2

__10. Аналіз індустрій серед високооплачуваних віддалених працівників:__

In [168]:
salary_limit = df['ConvertedCompYearly'].quantile(0.75)
salary_limit

np.float64(120596.0)

In [184]:
rich_remote = (df['ConvertedCompYearly'] > salary_limit) & (df['RemoteWork'] == 'Remote')
top_rich_remote = df[rich_remote]

result = top_rich_remote['Industry'].value_counts()
result

Industry
Software Development                          1186
Fintech                                        190
Healthcare                                     188
Other:                                         176
Internet, Telecomm or Information Services     138
Banking/Financial Services                      88
Government                                      78
Media & Advertising Services                    75
Retail and Consumer Services                    65
Transportation, or Supply Chain                 63
Computer Systems Design and Services            59
Insurance                                       46
Energy                                          45
Manufacturing                                   33
Higher Education                                30
Name: count, dtype: int64